workflows:
  ios_build:
    name: iOS Build from ZIP
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Unzip iOS project
        script: |
          echo "Unzipping iOS source..."
          unzip -o ios_app.zip -d .
          echo "Contents after unzip:"
          ls -al

      - name: Install CocoaPods dependencies
        script: |
          cd MyApp   # 👈 CHANGE THIS to your actual folder name
          if [ -f "Podfile" ]; then
            pod install --repo-update
          else
            echo "⚠️ No Podfile found, skipping pod install."
          fi

      - name: Build iOS app
        script: |
          cd MyApp   # 👈 same folder name here
          xcodebuild \
            -project MyApp.xcodeproj \
            -scheme MyApp \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates
