workflows:
  ios_build:
    name: Build iOS BarberSalon App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Unzip iOS source
        script: |
          echo "Unzipping project..."
          # The files (including Podfile and BarberSalon.xcworkspace) will be placed here (the current working directory)
          unzip -o ios_app.zip -d .
          echo "Unzipped files:"
          ls -R .

      - name: Locate project folder
        script: |
          # No change in directory is needed, just verify
          echo "Locating iOS project..."
          echo "Now inside folder:"
          pwd
          ls -al

      - name: Install dependencies
        script: |
          # The working directory is already correct (where Podfile is located)
          echo "Installing CocoaPods..."
          if [ -f "Podfile" ]; then
            pod install --repo-update # This creates the required BarberSalon.xcworkspace
          else
            echo "No Podfile found — skipping pod install."
          fi

      - name: Build iOS app
        script: |
          # The working directory is already correct (where BarberSalon.xcworkspace is located)
          echo "Building BarberSalon..."
          xcodebuild \
            -workspace BarberSalon.xcworkspace \
            -scheme BarberSalon \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
