workflows:
  ios_build:
    name: Build iOS BarberSalon App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest

    scripts:
      - name: Unzip iOS source
        script: |
          echo "📦 Unzipping project..."
          unzip -o ios_app.zip -d .
          echo "✅ Unzipped files:"
          ls -R

      - name: Locate iOS project folder
        script: |
          echo "🔍 Locating BarberSalon.xcodeproj..."
          FOLDER=$(find . -type f -name "BarberSalon.xcodeproj" | head -1 | xargs dirname)
          if [ -z "$FOLDER" ]; then
            echo "❌ BarberSalon.xcodeproj not found!"
            exit 1
          fi
          echo "✅ Found Xcode project in: $FOLDER"
          echo "FOLDER=$FOLDER" >> $CM_ENV_PATH
