workflows:
  upload_ipa:
    name: Upload Existing IPA to TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 10
    environment:
      vars:
        APP_STORE_CONNECT_KEY_IDENTIFIER: "2b6f56a9-4f08-4f55-97f1-567a817f2120"
        APP_STORE_CONNECT_ISSUER_ID: "GP6YCZ76LL"
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDa2oAe8d/D34oaS090NDanYhY7S0/SJ7gm/7bN9OF8KgCgYIKoZIzj0DAQehRANCAARP1E6GWHa3frSBWgwVAYoObX06zItsEM6K01yBsryXddyDNhVQwrXU4JtTBV017dhwkj7kzwye6QzQnfh7KM2A)
    scripts:
      - name: Upload .ipa to TestFlight
        script: |
          xcrun altool --upload-app \
            -f "MedianApp.ipa" \
            -t ios \
            --apiKey $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --apiIssuer $APP_STORE_CONNECT_ISSUER_ID
