workflows:
  ios_build:
    name: Build iOS BarberSalon App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Extract iOS source
        script: |
          echo "Extracting iOS source..."
          if [ -f "ios_app.zip" ]; then
            echo "Found ios_app.zip — extracting..."
            unzip -o ios_app.zip -d .
          elif [ -f "ios_source.tar.gz" ]; then
            echo "Found ios_source.tar.gz — extracting..."
            tar -xzf ios_source.tar.gz -C .
          else
            echo "❌ ERROR: No iOS source archive found!"
            exit 1
          fi
          echo "✅ Extraction complete. Here’s the folder structure:"
          find . -maxdepth 3

      - name: Install dependencies
        script: |
          echo "Installing CocoaPods..."
          if [ -f "Podfile" ]; then
            pod install --repo-update
          else
            echo "No Podfile found — skipping pod install."
          fi

      - name: Build iOS app
        script: |
          echo "Building BarberSalon..."
          WORKSPACE_PATH=$(find . -name "BarberSalon.xcworkspace" | head -n 1)
          if [ -z "$WORKSPACE_PATH" ]; then
            echo "❌ ERROR: BarberSalon.xcworkspace not found!"
            find . -maxdepth 4
            exit 1
          fi
          PROJECT_DIR=$(dirname "$WORKSPACE_PATH")
          cd "$PROJECT_DIR"
          echo "✅ Found workspace at: $WORKSPACE_PATH"
          echo "📂 Now inside directory: $(pwd)"
          xcodebuild \
            -workspace BarberSalon.xcworkspace \
            -scheme BarberSalon \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
