workflows:
  ios_build:
    name: Build iOS BarberSalon App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Unzip iOS source
        script: |
          set -e # Exit immediately if any command fails
          echo "Unzipping project..."
          unzip -o ios_app.zip -d .
          echo "Files after unzip:"
          ls -F # List files in the current directory

      - name: Install dependencies
        script: |
          set -e
          echo "Installing CocoaPods..."
          if [ -f "Podfile" ]; then
            pod install --repo-update
            echo "Files after pod install:"
            ls -F # <<< CHECK: This output MUST show BarberSalon.xcworkspace
          else
            echo "No Podfile found — skipping pod install."
          fi

      - name: Build iOS app
        script: |
          set -e
          echo "Verifying workspace existence before build:"
          if [ ! -d "BarberSalon.xcworkspace" ]; then
            echo "ERROR: BarberSalon.xcworkspace was NOT found in the current directory. Directory contents:"
            ls -F
            exit 1 # Fail the script if the workspace is missing
          fi

          echo "Building BarberSalon..."
          xcodebuild \
            -workspace BarberSalon.xcworkspace \
            -scheme BarberSalon \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
