workflows:
  ios_build:
    name: Build iOS BarberSalon App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Unzip iOS source
        script: |
          echo "Unzipping project..."
          unzip -o ios_app.zip -d .
          echo "Unzipped files:"
          ls -R .
          # Assuming the unzip operation places files directly in the working directory ('.')

      - name: Locate project folder
        script: |
          echo "Locating iOS project..."
          # Since the files are in the root directory, we just list them for verification
          echo "Now inside folder:"
          pwd
          ls -al

# --- Changes start here ---

      - name: Install dependencies
        script: |
          # No need for 'cd ios_source/ios'
          echo "Installing CocoaPods..."
          if [ -f "Podfile" ]; then
            pod install --repo-update
          else
            echo "No Podfile found — skipping pod install."
          fi

      - name: Build iOS app
        script: |
          echo "Building BarberSalon..."

          # Find the .xcworkspace path automatically
          WORKSPACE_PATH=$(find . -name "BarberSalon.xcworkspace" | head -n 1)

          if [ -z "$WORKSPACE_PATH" ]; then
            echo "❌ ERROR: BarberSalon.xcworkspace not found!"
            echo "Here are the files in current directory:"
            ls -R .
            exit 1
          fi

          # Move into the workspace directory
          PROJECT_DIR=$(dirname "$WORKSPACE_PATH")
          cd "$PROJECT_DIR"

          echo "✅ Found workspace at: $WORKSPACE_PATH"
          echo "📂 Now inside directory: $(pwd)"

          # Build the project
          xcodebuild \
            -workspace BarberSalon.xcworkspace \
            -scheme BarberSalon \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates


# --- Changes end here ---

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
