workflows:
  ios_build:
    name: Build iOS BarberSalon App (TAR.GZ Source)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Extract iOS source
        script: |
          echo "📦 Extracting iOS source..."
          tar -xzf ios_source.tar.gz -C .
          echo "✅ Extracted files:"
          ls -R .

      - name: Locate project folder
        script: |
          echo "🔍 Locating BarberSalon.xcworkspace..."
          FOLDER=$(find . -type f -name "BarberSalon.xcworkspace" | head -1 | xargs dirname)
          if [ -z "$FOLDER" ]; then
            echo "❌ BarberSalon.xcworkspace not found after extraction!"
            exit 1
          fi
          echo "✅ Found project folder: $FOLDER"
          echo "$FOLDER" > folder_path.txt

      - name: Install dependencies
        script: |
          FOLDER=$(cat folder_path.txt)
          cd "$FOLDER"
          echo "📦 Installing CocoaPods..."
          if [ -f "Podfile" ]; then
            pod install --repo-update
          else
            echo "⚠️ No Podfile found — skipping pod install."
          fi

      - name: Build iOS app
        script: |
          FOLDER=$(cat folder_path.txt)
          cd "$FOLDER"
