workflows:
  ios_build:
    name: Build iOS BarberSalon App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Debug: List source files before unzip
        script: |
          echo "Files in current directory:"
          ls -F

      - name: Unzip iOS source
        script: |
          set -e # Exit immediately if any command fails
          echo "Unzipping project..."
          
          # Try to unzip the expected file, or any other zip file found.
          if [ -f "ios_app.zip" ]; then
            unzip -o ios_app.zip -d .
          elif ls *.zip 1> /dev/null 2>&1; then
            echo "ios_app.zip not found. Attempting to unzip the first zip file found."
            unzip -o *.zip -d .
          else
            echo "FATAL ERROR: No zip file found. Ensure your source code is uploaded as a .zip file."
            exit 9
          fi
          
          echo "Unzipped files (should include Podfile and project folders):"
          ls -F

      - name: Install dependencies and create workspace
        script: |
          set -e
          # Ensure we are in the directory containing the Podfile
          echo "Installing CocoaPods..."
          if [ -f "Podfile" ]; then
            # This command generates the required 'BarberSalon.xcworkspace' file.
            pod install --repo-update
            echo "Files after pod install (MUST include BarberSalon.xcworkspace/):"
            ls -F
          else
            echo "ERROR: Podfile not found. Cannot proceed with CocoaPods installation."
            exit 1
          fi

      - name: Build iOS app
        script: |
          set -e
          
          # Verify the workspace exists before building
          if [ ! -d "BarberSalon.xcworkspace" ]; then
            echo "ERROR: 'BarberSalon.xcworkspace' not found. Check 'pod install' logs above."
            exit 1
          fi
          
          echo "Building BarberSalon..."
          # Use the generated workspace and the defined scheme
          xcodebuild \
            -workspace BarberSalon.xcworkspace \
            -scheme BarberSalon \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
