workflows:
  ios_build:
    name: iOS Build (App Store)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - appstore_credentials        # 👈 contains Issuer ID, Key ID, and private key
      vars:
        XCODE_PROJECT: "MyApp.xcodeproj"
        XCODE_SCHEME: "MyApp"
        BUNDLE_ID: "com.amirosama.myapp"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          cd ios_app
          pod install --repo-update || pod install

      - name: Build iOS app for App Store
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            -destination generic/platform=iOS

    artifacts:
      - ios_app/build/**/*.ipa
      - ios_app/build/**/*.xcarchive
      - ios_app/build/**/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
