workflows:
  ios_build:
    name: Build iOS BarberSalon App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Unzip iOS source
        script: |
          echo "Unzipping project..."
          unzip -o ios_app.zip -d .
          echo "Unzipped files:"
          ls -al

      - name: Install dependencies
        script: |
          echo "Installing CocoaPods..."
          # Automatically detect where BarberSalon.xcworkspace is
          FOLDER=$(find . -type f -name "BarberSalon.xcworkspace" | head -1 | xargs dirname)
          echo "Found project folder: $FOLDER"
          cd "$FOLDER"
          
          if [ -f "Podfile" ]; then
            pod install --repo-update
          else
            echo "No Podfile found — skipping pod install."
          fi

      - name: Build iOS app
        script: |
          cd "$FOLDER"
          echo "Building BarberSalon..."
          xcodebuild \
            -workspace BarberSalon.xcworkspace \
            -scheme BarberSalon \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
