workflows:
  upload_ipa:
    name: Upload Existing IPA to TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 10
    environment:
      vars:
        APP_STORE_CONNECT_KEY_IDENTIFIER: "YOUR_KEY_ID"
        APP_STORE_CONNECT_ISSUER_ID: "YOUR_ISSUER_ID"
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(YOUR_P8_KEY_CONTENT)
    scripts:
      - name: Upload .ipa to TestFlight
        script: |
          xcrun altool --upload-app \
            -f "MedianApp.ipa" \
            -t ios \
            --apiKey $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --apiIssuer $APP_STORE_CONNECT_ISSUER_ID
