workflows:
  ios_build:
    name: Build iOS BarberSalon App
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Unzip iOS source
        script: |
          set -e # Exit immediately if any command fails
          echo "Unzipping project..."
          # Unzip into the current working directory ('.')
          unzip -o ios_app.zip -d .
          echo "Files after unzip (should include Podfile):"
          ls -F

      - name: Install dependencies and create workspace
        script: |
          set -e
          echo "Installing CocoaPods..."
          if [ -f "Podfile" ]; then
            # 'pod install' must run successfully to generate 'BarberSalon.xcworkspace'
            pod install --repo-update
            echo "Files after pod install (MUST include BarberSalon.xcworkspace/):"
            ls -F
          else
            echo "ERROR: Podfile not found. Cannot proceed with CocoaPods installation."
            exit 1
          fi

      - name: Build iOS app
        script: |
          set -e
          # Verify the workspace exists before building
          if [ ! -d "BarberSalon.xcworkspace" ]; then
            echo "ERROR: 'BarberSalon.xcworkspace' not found after 'pod install'. Check logs above."
            exit 1
          fi
          
          echo "Building BarberSalon..."
          xcodebuild \
            -workspace BarberSalon.xcworkspace \
            -scheme BarberSalon \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates

    artifacts:
      - build/**/*.ipa
      - build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
